FROM node:7.4-alpine

COPY entrypoint /usr/local/bin

WORKDIR /usr/src/app/botwars/client

#Install gulp
RUN npm install -g gulp

EXPOSE 3000/tcp
EXPOSE 35729/tcp

ENTRYPOINT /usr/local/bin/entrypoint
